---
title: Atl Deals
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Atl Deals description...
baseurl: 
url: http:/atl.pink
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
